### ISSUE TITLE
Does expo-quick-action only work when app is on background?

### ISSUE THREAD

**Issue by ryzencool** [EvanBacon/expo-quick-actions#30]

**Comment by mbcod3** [comment]
yes it seems that is the case since QuickActions.setItems([ is called inside useEffect.

I think static ios actions set in plugin config might work even the app is closed

**Comment by EvanBacon** [comment]
Use the Config Plugin to set actions at build time https://github.com/EvanBacon/expo-quick-actions?tab=readme-ov-file#config-plugin

**Comment by mbcod3** [comment]
@EvanBacon on the read me page it says: "Static Android actions are not currently supported because they don't support complex intent.".
Just to confirm using the config plugin to set actions at build time is only supported for ios, right?
