### ISSUE TITLE
useQuickActionRouting Only Triggers on Initial App Start, Not in Background State

### ISSUE THREAD

**Issue by JustJoostNL** [EvanBacon/expo-quick-actions#31]
Hi!

I'm having an issue with the `useQuickActionRouting` hook. When the app is fully closed, the hook correctly intercepts actions. However, if the app is only in the background (not completely killed), the action isn’t picked up.

**Comment by TomCorvus** [comment]
I have the same issue. 
Without having more information about your environment, it's difficult to help.

But in my case, this problem appears since Expo52 and RN0.76.

I think the package is not compatible with Expo52 yet.

@EvanBacon any plan to update the package to make it compatible?

Thank you.

**Comment by JustJoostNL** [comment]
I am also using SDK52 and RN 0.76. I don’t know if this happened since I only used it since SDK52.
________________________________

**Comment by TomCorvus** [comment]
I confirm that listener works on Expo51/RN0.75 when the app is in background or closed so the author have to make it compatible with Expo52.

**Comment by joshmohrer** [comment]
Paging Dr. @EvanBacon :)

**Comment by alextoudic** [comment]
I encountered the same issue after upgrading to Expo 52

After digging into it, I've been able to make it work and submitted an upgrade on https://github.com/EvanBacon/expo-quick-actions/pull/32

In the meantime I'm using the following patch [expo-quick-actions-npm-2.0.0-48c4cc5a85.patch](https://github.com/user-attachments/files/17970406/expo-quick-actions-npm-2.0.0-48c4cc5a85.patch)

**Comment by JustJoostNL** [comment]
Closing this as I can confirm this is fixed in the latest release.
