### ISSUE TITLE
Expo Go App support

### ISSUE THREAD

**Issue by jtvargas** [EvanBacon/expo-quick-actions#5]
Is this library supported using the Expo Go App? If that's the case what would be the installation process?

**Comment by mphill** [comment]
It would not be as it requires native code, however, this should be included officially.  Surprised to find it's not.  Even MAUI supports this:  https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/app-actions?view=net-maui-8.0&tabs=android

**Comment by EvanBacon** [comment]
This is not planned for Expo Go and likely never will be.
