### ISSUE TITLE
QuickActions orders

### ISSUE THREAD

**Issue by popejs** [EvanBacon/expo-quick-actions#6]
I had to reverse the quick actions order in iOS to maintain the same order as Android.  It was confusing to me at first on how to achieve the same order.  I did the following:

`  QuickActions.setItems(Platform.OS === 'ios' ? items.reverse() : items);`

**Comment by EvanBacon** [comment]
The quick actions order is based on the placement relative to the screen, it's chosen by the OS. I don't think it makes sense (at the moment) to flip the native behavior on a single platform.
